spring.application.name=auth
spring.config.import=optional:configserver:http://localhost:8888
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8080/eureka
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://turntable.proxy.rlwy.net:30198/grota_auth
spring.datasource.username=admin
spring.datasource.password=lEwwdChduIZKfqqiKnQFmqhaElNQNjDM
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

auth.jwt.secret=change-me-to-a-strong-secret-key-32-bytes-min
auth.jwt.access-token-ttl=PT15M
auth.jwt.refresh-token-ttl=P7D
auth.code.ttl=PT10M

spring.security.user.name=admin
spring.security.user.password=admin

# Configuracao de e-mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:vinicius.nextjs@gmail.com}
spring.mail.password=${MAIL_PASSWORD:pbyq kxmh mxsb bruh}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

