services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${API_IMAGE_NAME:-grota/api-service}:${API_IMAGE_TAG:-local}
    container_name: api_service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL:-jdbc:postgresql://ep-wandering-mud-aitgemhn-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require}"
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-neondb_owner}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-npg_j6fOmux3DKTQ}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:-org.postgresql.Driver}
      SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM:-org.hibernate.dialect.PostgreSQLDialect}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL:-false}
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: ${SPRING_JPA_FORMAT_SQL:-false}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-update}
      LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER: INFO
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-change-me-with-at-least-32-chars}
      SWAGGER_AUTH_USERNAME: ${SWAGGER_AUTH_USERNAME:-swagger}
      SWAGGER_AUTH_PASSWORD: ${SWAGGER_AUTH_PASSWORD:-swagger123}
      APP_SECURITY_COOKIES_SECURE: ${APP_SECURITY_COOKIES_SECURE:-false}
      APP_SECURITY_COOKIES_SAME_SITE: ${APP_SECURITY_COOKIES_SAME_SITE:-Lax}
      MAIL_USERNAME: ${MAIL_USERNAME:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}
      APP_MAIL_FROM: ${APP_MAIL_FROM:-no-reply@thousandtws.digital}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
    ports:
      - "${API_PORT:-8080}:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
