spring.application.name=service-discovery

server.port=8080

spring.docker.compose.enabled=false

spring.cloud.config.server.git.uri=
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.search-paths=config

eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.client.service-url.defaultZone=http://localhost:8080/eureka
eureka.server.enable-self-preservation=false
eureka.instance.hostname=localhost

# Swagger UI aggregator
springdoc.swagger-ui.urls[0].name=auth
springdoc.swagger-ui.urls[0].url=http://192.168.1.9:8081/v3/api-docs
springdoc.swagger-ui.urls[1].name=service-discovery
springdoc.swagger-ui.urls[1].url=http://192.168.1.9:8080/v3/api-docs
