spring.datasource.url=jdbc:postgresql://localhost:5433/prod_db
spring.datasource.username=prod_user
spring.datasource.password=prod_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false

spring.jpa.hibernate.ddl-auto=validate

#Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
cloudinary.dealer-logo-folder=${CLOUDINARY_DEALER_FOLDER:dealer-logos}
swagger.auth.username=${SWAGGER_AUTH_USERNAME:swagger}
swagger.auth.password=${SWAGGER_AUTH_PASSWORD:change-me}

jwt.secret=${JWT_SECRET:VGhpcy1pcy1hLXNlY3VyZS1rZXktMzItYnl0ZXMtbG9uZw==}
# 2 horas em milissegundos
jwt.expiration=7200000
# 7 dias em milissegundos
jwt.refresh-token.expiration=604800000

# Cookies (produção com HTTPS)
app.security.cookies.secure=true
app.security.cookies.same-site=None
