#Config database para o banco Postgres
spring.datasource.url=jdbc:postgresql://ballast.proxy.rlwy.net:44529/railway
spring.datasource.username=postgres
spring.datasource.password=GDxNPTsBNZUYpfZAQQBideXOFdDxBqoX
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Configuracao  JWT TOKEN
jwt.secret=${JWT_SECRET_KEY:hfQHt0760CYWNn6uxuInZCaEkmK5mVvZWsJMVbdaLdzGB9rXC7JFJGr8wSw=}
# 2 horas em milissegundos 
jwt.expiration=${JWT_EXPIRATION_TIME:7200000}
# 7 dias em milissegundos
jwt.refresh-token.expiration=${JWT_REFRssESH_TOKEN_EXPIRATION_TIME:604800000}

# Configuraes Spring Multipart (Upload de arquivos)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#URL para acessar o swagger
springdoc.swagger-ui.path=/swagger-ui.html
swagger.auth.username=${SWAGGER_AUTH_USERNAME:swagger}
swagger.auth.password=${SWAGGER_AUTH_PASSWORD:swagger123}

# Cookies (ambiente local sem HTTPS)
app.security.cookies.secure=false
app.security.cookies.same-site=Lax

#Configuracao de e-mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:vinicius.nextjs@gmail.com}
spring.mail.password=${MAIL_PASSWORD:pbyq kxmh mxsb bruh}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${email:teste@gmail.com}

#Cloudinary (upload logomarca/documentos)
cloudinary.cloud-name=dao3brh15
cloudinary.api-key=298785541169335
cloudinary.api-secret=SSdIDShQBxU8tGymNM5s749SALU
cloudinary.dealer-logo-folder=${CLOUDINARY_DEALER_FOLDER:dealer-logos}
cloudinary.documents-folder=${CLOUDINARY_DOCUMENTS_FOLDER:documents}
