import type { Conversation, EmployeeSummary } from "./types";

export const mockEmployees: EmployeeSummary[] = [
  { id: "emp-1", name: "Camila Rocha", role: "Supervisora", status: "online", load: 12 },
  { id: "emp-2", name: "Marcos Vinicius", role: "Atendimento", status: "ocupado", load: 8 },
  { id: "emp-3", name: "Ana Beatriz", role: "Atendimento", status: "online", load: 5 },
  { id: "emp-4", name: "Rafael Gomes", role: "Qualificação", status: "offline", load: 0 },
];

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    customerName: "Fernanda Alves",
    customerPhone: "(19) 99922-8411",
    customerSegment: "Lead quente",
    verified: true,
    avatarColor: "from-emerald-300 to-emerald-500",
    unreadCount: 3,
    stage: "em_atendimento",
    assignedTo: mockEmployees[0],
    lastSeenLabel: "12:18",
    tags: ["Financiamento", "Leves", "Entrada alta"],
    proposalCode: "PROP-24031",
    vehicleLabel: "Tracker 2023 LT Turbo",
    previews: [
      {
        id: "preview-1",
        type: "text",
        content: "cliente: Tenho interesse em seguir com a proposta.",
        status: "read",
        pinned: true,
      },
      {
        id: "preview-2",
        type: "voice",
        content: "cliente: Audio recebido",
        duration: "0:08",
        status: "voice",
      },
    ],
    messages: [
      {
        id: "m-1",
        direction: "outbound",
        author: "Camila Rocha",
        content: "Oi, Fernanda. Recebi sua solicitação e já estou acompanhando a proposta.",
        timestamp: "22/03 11:54",
        status: "read",
      },
      {
        id: "m-2",
        direction: "inbound",
        author: "Fernanda Alves",
        content: "Perfeito. Quero entender a melhor condição com entrada de R$ 18 mil.",
        timestamp: "22/03 11:57",
      },
      {
        id: "m-3",
        direction: "outbound",
        author: "Camila Rocha",
        content: "Conseguimos trabalhar em 48x com aprovação prioritária. Vou enviar a simulação refinada.",
        timestamp: "22/03 12:02",
        status: "read",
      },
      {
        id: "m-4",
        direction: "inbound",
        author: "Fernanda Alves",
        content: "Ótimo, pode seguir. Se possível quero concluir hoje.",
        timestamp: "22/03 12:18",
      },
    ],
  },
  {
    id: "conv-2",
    customerName: "Ricardo Monteiro",
    customerPhone: "(11) 98872-1200",
    customerSegment: "Recuperação",
    avatarColor: "from-sky-300 to-cyan-500",
    unreadCount: 0,
    stage: "aguardando_cliente",
    assignedTo: mockEmployees[1],
    lastSeenLabel: "11:46",
    tags: ["Reativação", "PJ"],
    proposalCode: "PROP-23987",
    vehicleLabel: "Hilux 2022 SRX",
    previews: [
      {
        id: "preview-3",
        type: "text",
        content: "operador: Enviamos a documentação para validação.",
        status: "delivered",
      },
    ],
    messages: [
      {
        id: "m-5",
        direction: "outbound",
        author: "Marcos Vinicius",
        content: "Ricardo, faltou apenas o comprovante de faturamento para seguir.",
        timestamp: "22/03 11:30",
        status: "delivered",
      },
    ],
  },
  {
    id: "conv-3",
    customerName: "Larissa Prado",
    customerPhone: "(31) 99762-4410",
    customerSegment: "Novo lead",
    avatarColor: "from-fuchsia-300 to-pink-500",
    unreadCount: 1,
    stage: "novo",
    assignedTo: mockEmployees[2],
    lastSeenLabel: "10:14",
    tags: ["Moto", "Primeiro contato"],
    proposalCode: "PROP-24052",
    vehicleLabel: "Honda PCX 2024 ABS",
    previews: [
      {
        id: "preview-4",
        type: "text",
        content: "cliente: Queria saber a entrada mínima para começar.",
        status: "delivered",
      },
    ],
    messages: [
      {
        id: "m-6",
        direction: "inbound",
        author: "Larissa Prado",
        content: "Queria saber a entrada mínima para começar.",
        timestamp: "22/03 10:14",
      },
    ],
  },
  {
    id: "conv-4",
    customerName: "Grupo Atlanta Frotas",
    customerPhone: "(21) 98111-2299",
    customerSegment: "Conta estratégica",
    verified: true,
    avatarColor: "from-amber-300 to-orange-500",
    unreadCount: 0,
    stage: "finalizado",
    assignedTo: mockEmployees[0],
    lastSeenLabel: "Ontem",
    tags: ["Frota", "Pesados"],
    proposalCode: "PROP-23812",
    vehicleLabel: "Sprinter 417 CDI",
    previews: [
      {
        id: "preview-5",
        type: "text",
        content: "supervisora: Atendimento concluído com envio de contrato.",
        status: "read",
      },
    ],
    messages: [
      {
        id: "m-7",
        direction: "outbound",
        author: "Camila Rocha",
        content: "Contrato emitido e enviado para assinatura. Seguimos monitorando o retorno.",
        timestamp: "21/03 18:40",
        status: "read",
      },
    ],
  },
];
