ALTER TABLE users
    ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone VARCHAR(30);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS cpf VARCHAR(20);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS address VARCHAR(255);
