"use client";

export const DEFAULT_HISTORY_LIMIT = 50;
export const DEFAULT_RECONNECT_DELAY = 2500;

export const REALTIME_CHANNELS = {
  CHAT: "admin-logista",
  PROPOSALS: "proposals-bridge",
  DEALERS: "dealers-bridge",
  NOTIFICATIONS: "notifications-bridge",
  DOCUMENTS: "documents-bridge",
};

export const REALTIME_EVENT_TYPES = {
  PROPOSALS_REFRESH_REQUEST: "PROPOSALS_REFRESH_REQUEST",
  PROPOSAL_CREATED: "PROPOSAL_CREATED",
  PROPOSAL_STATUS_UPDATED: "PROPOSAL_STATUS_UPDATED",
  PROPOSAL_EVENT_APPENDED: "PROPOSAL_EVENT_APPENDED",
  DEALER_REFRESH_REQUEST: "DEALER_REFRESH_REQUEST",
  DEALER_UPSERTED: "DEALER_UPSERTED",
  DEALER_DELETED: "DEALER_DELETED",
  NOTIFICATION_PUBLISHED: "NOTIFICATION_PUBLISHED",
  NOTIFICATION_DISMISS: "NOTIFICATION_DISMISS",
  SELLER_ACTIVITY_SENT: "SELLER_ACTIVITY_SENT",
  DOCUMENTS_REFRESH_REQUEST: "DOCUMENTS_REFRESH_REQUEST",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_REVIEW_UPDATED: "DOCUMENT_REVIEW_UPDATED",
};
